// <auto-generated />
namespace Veme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemoveCouponDurationInMonthsColumnFromOffersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveCouponDurationInMonthsColumnFromOffersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090301419_RemoveCouponDurationInMonthsColumnFromOffersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
